import { build } from 'esbuild';
import { readFile, writeFile } from 'node:fs/promises';
const result=await build({entryPoints:['scene/standalone.ts'],bundle:true,minify:true,write:false,format:'iife',target:['es2020'],legalComments:'inline'});
const css=(await readFile('app/globals.css','utf8')).replace("@import 'tailwindcss';",'');
const js=result.outputFiles[0].text.replace(/<\/script/gi,'<\\/script');
const html=`<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Christmas Corner · 3D Miniature Shop</title><style>${css}</style></head><body><main><div id="scene" class="scene"></div><header class="chapter-intro"><span class="edition">NO. 01 / WINTER MINIATURE</span><h1>Christmas Corner</h1><p>A little shop full of winter warmth</p></header><div class="time-controls"><button class="time-button" id="time-toggle" aria-pressed="false" aria-label="Switch to night mode"><span class="control-label">Night mode</span></button><div class="weather-controls" role="group" aria-label="Weather"><button class="weather-button" data-weather="sunny" aria-pressed="true"><span class="control-label">Sunny</span></button><button class="weather-button" data-weather="cloudy" aria-pressed="false"><span class="control-label">Cloudy</span></button><button class="weather-button" data-weather="snowy" aria-pressed="false"><span class="control-label">Snowy</span></button></div></div><footer><div><span class="tag">LA MAISON DE NOËL</span><p>Drag to rotate · Scroll to zoom · Try switching the weather!</p></div><button id="reset" class="reset-button" aria-label="Reset camera view"><svg class="reset-icon" viewBox="0 0 20 20" aria-hidden="true" fill="currentColor"><path d="M3 2h2v3h2V3h7v2h3v3h2v7h-2v3h-3v2H7v-2H4v-3H2v-4h2v4h3v3h7v-3h3V8h-3V5H7v2h2v2H3z"/></svg>Reset</button></footer></main><script>${js}</script></body></html>`;
await writeFile('圣诞商店.html',html,'utf8');
console.log('Created standalone HTML: '+Math.round(Buffer.byteLength(html)/1024)+' KB; all scripts embedded.');

